version: "3.9"

services:
  mysql:
    image: mysql:8.0
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_R2DBC_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SPRING_R2DBC_DATABASE}
      MYSQL_USER: ${SPRING_R2DBC_USER}
      MYSQL_PASSWORD: ${SPRING_R2DBC_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - ./mysql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql

  spring:
    image: crudtest-api:1.0
    restart: always
    env_file: .env

    environment:
      # Application
      SPRING_R2DBC_DATABASE: ${SPRING_R2DBC_DATABASE}
      SPRING_R2DBC_USER: ${SPRING_R2DBC_USER}
      SPRING_R2DBC_PASSWORD: ${SPRING_R2DBC_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

      # OpenTelemetry
      JAVA_TOOL_OPTIONS: >
        -javaagent:/otel/opentelemetry-javaagent.jar

      OTEL_SERVICE_NAME: crudtest-api-local
      OTEL_EXPORTER_OTLP_ENDPOINT: https://${DYNATRACE_TENANT}.live.dynatrace.com/api/v2/otlp
      OTEL_EXPORTER_OTLP_HEADERS: Authorization=Api-Token\ ${DYNATRACE_API_TOKEN}

      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp

      OTEL_RESOURCE_ATTRIBUTES: >
        service.namespace=local,
        service.version=1.0.0,
        deployment.environment=localhost

      OTEL_LOG_LEVEL: info

    volumes:
      - ./opentelemetry-javaagent.jar:/otel/opentelemetry-javaagent.jar

    ports:
      - "8080:8080"

    networks:
      - backend

    depends_on:
      - mysql

networks:
  backend:
    driver: bridge
