

services:
  mysql:
    image: mysql:8.0
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_R2DBC_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SPRING_R2DBC_DATABASE}
      MYSQL_USER: ${SPRING_R2DBC_USER}
      MYSQL_PASSWORD: ${SPRING_R2DBC_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - ./mysql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql

  spring-dev:
    image: crudtest-api:1.0
    env_file: .env
    environment:
      #application.yml
      SPRING_R2DBC_DATABASE: ${SPRING_R2DBC_DATABASE}
      SPRING_R2DBC_USER: ${SPRING_R2DBC_USER}
      SPRING_R2DBC_PASSWORD: ${SPRING_R2DBC_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - mysql

networks:
  backend:
    driver: bridge